name: GetTag
on:
  release:
    types: [published]
    push:
jobs:
  get_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        run: |
          echo "${GITHUB_REF#refs/*/}"
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Changing version
        run: |
          echo "${GITHUB_REF#refs/*/}"
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          RELEASE_VERSION=(echo $RELEASE_VERSION | grep "[0-9]\+.[0-9]\+.[0-9]\+[a-z]*" -o)
          sed 's/version = ".\+"/version = "{$RELEASE_VERSION}"/g' pyproject.toml > pyproject.new.toml
          mv pyproject.new.toml pyproject.toml
          cat pyproject.toml