name: GetTag
on:
  release:
    types: [published]
jobs:
  get_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        run: |
          echo "${GITHUB_REF#refs/*/}"
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - run: |
          echo $RELEASE_VERSION