name: Publish to Test PyPI
on:
  push:
    tags:
      - '*.*.*'
jobs:
  test_pypi_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -
      - name: Add Poetry to path
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
      - run: poetry install
      - name: Changing version
        run: |
          echo "${GITHUB_REF#refs/*/}"
          RELEASE_VERSION="${GITHUB_REF#refs/*/}"
          RELEASE_VERSION=$(echo $RELEASE_VERSION | grep "[0-9]\+.[0-9]\+.[0-9]\+[a-z]*" -o)
          sed "s/version = \".\+\"/version = \"${RELEASE_VERSION}\"/g" pyproject.toml > pyproject.new.toml
          mv pyproject.new.toml pyproject.toml
      - run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      - run: poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_KEY }}
      - name: Publish package
        run: poetry publish --build -r testpypi
